"""Regenerate the fixed OLED Wi-Fi QR (pip install qrcode); firmware needs no QR library."""
from pathlib import Path
import qrcode

payload = 'WIFI:T:nopass;S:notfall.ms INFO;;'
qr = qrcode.QRCode(version=2, error_correction=qrcode.constants.ERROR_CORRECT_L, border=4, box_size=1)
# Seven-character alphanumeric WIFI:T: segment makes the full explicit nopass
# payload fit version 2-L, keeping the OLED symbol as small as possible.
qr.add_data(payload, optimize=7)
qr.make(fit=False)
matrix = qr.modules
assert len(matrix) == 25
rows = [sum(int(bit) << x for x, bit in enumerate(row)) for row in matrix]
content = '''// Generated by scripts/generate_wifi_qr.py. Payload: ''' + payload + '''
#pragma once
#include <stdint.h>
static const uint32_t safeMSWifiQrRows[25] = {
''' + ',\n'.join('  0x%08xUL' % row for row in rows) + '\n};\n'
target = Path(__file__).resolve().parents[1] / 'firmware/variants/sensebox_eye/SafeMSWifiQr.h'
target.write_text(content, encoding='ascii')
print('Generated version 2-L Wi-Fi QR, 25 modules plus four-module quiet zone')
