// Generated by scripts/generate_wifi_qr.py. Payload: WIFI:T:nopass;S:notfall.ms INFO;;
#pragma once
#include <stdint.h>
static const uint32_t safeMSWifiQrRows[25] = {
  0x01fd4a7fUL,
  0x01047741UL,
  0x0175405dUL,
  0x0174d55dUL,
  0x01750e5dUL,
  0x01047941UL,
  0x01fd557fUL,
  0x00010400UL,
  0x00aae1dfUL,
  0x0064170bUL,
  0x01df7956UL,
  0x01c80504UL,
  0x01dd90fdUL,
  0x001e568fUL,
  0x0177f269UL,
  0x008bbb15UL,
  0x007fc35dUL,
  0x01d11f00UL,
  0x00b5637fUL,
  0x0091ae41UL,
  0x013f435dUL,
  0x0135035dUL,
  0x011abf5dUL,
  0x00772941UL,
  0x016af37fUL
};
